version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.5

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          attach-workspace: false
          checkout: true
          orb-name: masutaka/tfupdate
          orb-path: orb.yml
          validate: true
          requires:
            - orb-tools/lint
