version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.5

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          attach-workspace: false
          checkout: true
          orb-name: masutaka/tfupdate
          orb-path: orb.yml
          store-artifact: false
          validate: true
          requires:
            - orb-tools/lint
      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          ssh-fingerprints: 9e:01:82:b2:99:b1:24:0b:0c:e7:c3:64:2f:0b:43:f1
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master
      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          ssh-fingerprints: 9e:01:82:b2:99:b1:24:0b:0c:e7:c3:64:2f:0b:43:f1
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master
