version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0

workflows:
  ordinary:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: masutaka/tfupdate
          requires:
            - orb-tools/lint
            - orb-tools/pack
      # If the commit message contains the below, the orb will be publish.
      # - [semver:major]
      # - [semver:minor]
      # - [semver:patch]
      # If the commit message contains the below or not, the orb will not be publish.
      # - [semver:skip]
      - orb-tools/dev-promote-prod-from-commit-subject:
          name: dev-promote-semver
          add-pr-comment: false
          fail-if-semver-not-indicated: false
          orb-name: masutaka/tfupdate
          publish-version-tag: true
          ssh-fingerprints: 9e:01:82:b2:99:b1:24:0b:0c:e7:c3:64:2f:0b:43:f1 # user key on https://circleci.com/gh/masutaka/circleci-tfupdate-orb/edit#checkout
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master
