version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0

workflows:
  ordinary:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: masutaka/tfupdate
          requires:
            - orb-tools/lint
            - orb-tools/pack
      # If the commit message contains the below, it will publish the new version and git-push new tag.
      #  [semver:major]
      #  [semver:minor]
      #  [semver:patch]
      # If the commit message contains the below or not, it will not publish the new version and not git-push new tag.
      #  [semver:skip]
      - orb-tools/dev-promote-prod-from-commit-subject:
          name: dev-promote-semver
          add-pr-comment: false
          fail-if-semver-not-indicated: false
          orb-name: masutaka/tfupdate
          publish-version-tag: true
          ssh-fingerprints: 69:c2:08:b5:9c:88:2c:e7:12:e2:b7:33:bd:ac:a4:e6 # User Key on https://app.circleci.com/settings/project/github/masutaka/circleci-tfupdate-orb/ssh
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master
